name = "affensus-web"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"
output_directory = "out"

[env.production]
name = "affensus-web"

[env.staging]
name = "affensus-web-staging"

