name = "affensus-web"
compatibility_date = "2024-01-01"

# Pages configuration
pages_build_output_dir = "out"

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "affensus-auth"
database_id = "19caf1fa-62ec-47ae-9429-9f3ff31a3b00"

# Environment variables
[vars]
SITE_URL = "http://localhost:3000"
JWT_SECRET = "your-super-secret-jwt-key-change-this-in-production"
# Add your Google OAuth credentials here:
# GOOGLE_CLIENT_ID = "your-google-client-id"
# GOOGLE_CLIENT_SECRET = "your-google-client-secret"
# RESEND_API_KEY = "your-resend-api-key"
# STRIPE_SECRET_KEY = "your-stripe-secret-key"

[env.production]
name = "affensus-web"

[env.production.vars]
# Add your production environment variables here
# UPTIME_KUMA_URL = "https://your-uptime-kuma-domain.com"

[env.preview]
name = "affensus-web-preview"

[env.preview.vars]
# Add your preview environment variables here  
# UPTIME_KUMA_URL = "https://your-preview-uptime-kuma-domain.com"

